name: GeoMinX
channels:
  - conda-forge
  - defaults

dependencies:
  - python
  - geopandas
  - pandas
  - numpy
  - tqdm
  - shapely
  - geopy
  - atlite
  - pypsa
  - matplotlib
  - cartopy
  - gdal
  - openpyxl
  - xarray
  - fiona
  - pyproj
  - rasterio
  - pillow
  - cdsapi
  - contextily
  - requests
  - aiohttp
  - geodatasets
  - unidecode
  - gurobi::gurobi

